on:
  pull_request:
jobs:
  check_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: bar
        shell: bash
        run: |
          ls -halF
          git rev-parse HEAD
