on:
  pull_request_target:
jobs:
  check_pr_target:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: foo
        shell: bash
        run: |
          ls -halF
          git rev-parse HEAD
